---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: LoggedInBetaUsers

description: ""

conditions:
  allOf:
    - property:
        name: isLoggedIn
        operator: is-true
    - property:
        name: isBetaUser
        operator: is-true
